import type { Question } from "@twih/game-core";

/**
 * Local mock data for Phase 2 development only — NOT the real seed content.
 * The real 30-day/150-question seed set (fact-checked, verified: true) is a
 * separate deliverable that lands with the backend/admin phases. Every entry
 * here is deliberately `verified: false`.
 */
export const mockQuestions: Question[] = [
  {
    id: "mock-croissant",
    prompt: "The croissant's ancestor, the kipferl, was first baked here.",
    category: "bread-pastry",
    difficulty: 1,
    answer: { lat: 48.2082, lng: 16.3738 },
    answerRadiusKm: 50,
    funFact:
      "The kipferl predates the croissant by centuries and was already a Viennese staple before French bakers adapted it into the laminated croissant we know today.",
    sourceUrl: "https://en.wikipedia.org/wiki/Kipferl",
    verified: false,
  },
  {
    id: "mock-margherita",
    prompt: "Pizza Margherita was created in this city, legend says for a queen.",
    category: "national-dishes",
    difficulty: 1,
    answer: { lat: 40.8518, lng: 14.2681 },
    answerRadiusKm: 30,
    funFact:
      "Naples is widely credited with the modern pizza; the Margherita's red, white, and green toppings are said to echo the Italian flag.",
    sourceUrl: "https://en.wikipedia.org/wiki/Pizza_Margherita",
    verified: false,
  },
  {
    id: "mock-tequila",
    prompt: "Tequila takes its name from this town, where it's still distilled today.",
    category: "cocktails",
    difficulty: 2,
    answer: { lat: 20.8833, lng: -103.8333 },
    answerRadiusKm: 40,
    funFact: "Tequila can, by law, only be produced in specific regions of Mexico, mostly around the town of Tequila, Jalisco.",
    sourceUrl: "https://en.wikipedia.org/wiki/Tequila",
    verified: false,
  },
  {
    id: "mock-champagne",
    prompt: "Sparkling wine can only legally be called by this name if it's from here.",
    category: "wine",
    difficulty: 2,
    answer: { lat: 49.0, lng: 4.0 },
    answerRadiusKm: 60,
    funFact: "The Champagne region of northeastern France gives its name — and, by EU law, exclusive rights to the name — to the sparkling wine.",
    sourceUrl: "https://en.wikipedia.org/wiki/Champagne",
    verified: false,
  },
  {
    id: "mock-feta",
    prompt: "This salty, crumbly cheese has protected-origin status tied to one country.",
    category: "cheese",
    difficulty: 2,
    answer: { lat: 39.0742, lng: 21.8243 },
    answerRadiusKm: 200,
    funFact: "Feta has Protected Designation of Origin status in the EU — only cheese made in Greece using traditional methods can be called feta.",
    sourceUrl: "https://en.wikipedia.org/wiki/Feta",
    verified: false,
  },
  {
    id: "mock-currywurst",
    prompt: "Currywurst, sausage doused in curry ketchup, was invented in this city after WWII.",
    category: "street-food",
    difficulty: 2,
    answer: { lat: 52.52, lng: 13.405 },
    answerRadiusKm: 30,
    funFact: "Herta Heuwer is credited with inventing currywurst in Berlin in 1949, using ketchup and curry powder she got from British soldiers.",
    sourceUrl: "https://en.wikipedia.org/wiki/Currywurst",
    verified: false,
  },
  {
    id: "mock-macaron",
    prompt: "The modern double-shell macaron (not the macaroon) was popularized by a pâtisserie here.",
    category: "desserts",
    difficulty: 2,
    answer: { lat: 48.8566, lng: 2.3522 },
    answerRadiusKm: 20,
    funFact: "Ladurée in Paris is often credited with inventing the sandwich-style macaron in the early 20th century.",
    sourceUrl: "https://en.wikipedia.org/wiki/Macaron",
    verified: false,
  },
  {
    id: "mock-espresso",
    prompt: "The espresso machine as we know it was patented and popularized in this city.",
    category: "coffee-tea",
    difficulty: 2,
    answer: { lat: 45.4642, lng: 9.19 },
    answerRadiusKm: 40,
    funFact: "Luigi Bezzera patented an early espresso machine in Milan in 1901, laying the groundwork for the modern cafe espresso shot.",
    sourceUrl: "https://en.wikipedia.org/wiki/Espresso_machine",
    verified: false,
  },
  {
    id: "mock-saffron",
    prompt: "Most of the world's saffron is grown in this country.",
    category: "spices",
    difficulty: 3,
    answer: { lat: 36.3, lng: 59.6 },
    answerRadiusKm: 300,
    funFact: "Iran produces roughly 90% of the world's saffron, concentrated in the Khorasan region.",
    sourceUrl: "https://en.wikipedia.org/wiki/Saffron",
    verified: false,
  },
  {
    id: "mock-pho",
    prompt: "Pho emerged in the early 1900s in northern cities of this country.",
    category: "national-dishes",
    difficulty: 2,
    answer: { lat: 21.0278, lng: 105.8342 },
    answerRadiusKm: 150,
    funFact: "Pho is widely believed to have originated in northern Vietnam, around Hanoi and Nam Dinh, in the early 20th century.",
    sourceUrl: "https://en.wikipedia.org/wiki/Pho",
    verified: false,
  },
  {
    id: "mock-mojito",
    prompt: "The mojito was born in bars in this capital city.",
    category: "cocktails",
    difficulty: 2,
    answer: { lat: 23.1136, lng: -82.3666 },
    answerRadiusKm: 30,
    funFact: "Havana, Cuba is the traditional birthplace of the mojito, with rum, mint, lime, sugar, and soda water.",
    sourceUrl: "https://en.wikipedia.org/wiki/Mojito",
    verified: false,
  },
  {
    id: "mock-gouda",
    prompt: "This cheese takes its name from a trading town, not where all of it is made.",
    category: "cheese",
    difficulty: 1,
    answer: { lat: 52.0116, lng: 4.7106 },
    answerRadiusKm: 40,
    funFact: "Gouda is named after the Dutch city where it was historically traded, not necessarily produced.",
    sourceUrl: "https://en.wikipedia.org/wiki/Gouda_cheese",
    verified: false,
  },
];
